import { activeFn } from '../registry/functions';
import { getCodeValue, getSigValue } from '../ui/editor';
import { parseSig } from '../parser/signature';

export function exportASM(): void {
  const fn = activeFn();
  if (!fn) return;

  fn.scalarCode = getCodeValue('scalar');
  fn.neonCode   = getCodeValue('neon');
  fn.sig        = getSigValue();
  fn.parsed     = parseSig(fn.sig);

  const name   = fn.parsed?.name ?? 'fn';
  const sig    = fn.sig || '@ (no signature)';

  const header = `@ ARM assembly export: ${name}\n@ Generated by NEONLab\n@\n@ Signature: ${sig}\n`;

  function fmtBlock(code: string, label: string): string {
    const lines = code
      .split('\n')
      .map(l => {
        const stripped = l.replace(/\/\/.*$/, '').trimEnd();
        return stripped ? '    ' + stripped : '';
      })
      .join('\n');
    return `\n@ ── ${label} ──────────────────────────────────────────\n    .text\n    .arm\n    .global ${label}\n    .type   ${label}, %function\n${label}:\n${lines}\n\n    .size ${label}, .-${label}\n`;
  }

  const text = header
    + fmtBlock(fn.scalarCode, name + '_scalar')
    + fmtBlock(fn.neonCode,   name + '_neon');

  const blob = new Blob([text], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = name + '.s'; a.click();
  URL.revokeObjectURL(url);
}
